const { test, expect } = require('@playwright/test');

test('Agent Console - Multi-chat management E2E', async ({ page }) => {
  const testEmail = `test-agent-features-${Date.now()}@example.com`;
  const testPassword = 'password123';

  // 1. Navigate to login and sign up
  await page.goto('/jobboard/login.html');
  await page.click('#toggleMode');
  await page.fill('#email', testEmail);
  await page.fill('#password', testPassword);
  await page.click('#submitBtn');

  // 2. Wait for redirect to Dashboard
  await page.waitForURL('**/index.html');
  await expect(page.locator('#welcomeTitle')).toContainText('Welcome back');

  // 3. Open the Agent Console
  const toggleBtn = page.locator('.agent-toggle-btn');
  await expect(toggleBtn).toBeVisible();
  await toggleBtn.click();

  const panel = page.locator('.agent-panel');
  await expect(panel).toHaveClass(/open/);

  // 4. Wait for WebSocket Connection
  const headerStatus = panel.locator('.agent-header-status');
  await expect(headerStatus).toContainText('Online', { timeout: 10000 });

  // 5. Send first user message to trigger dynamic auto-titling
  const inputField = panel.locator('.agent-input-field');
  const sendBtn = panel.locator('.agent-send-btn');
  await inputField.fill('Hola Zenith');
  await sendBtn.click();

  // Wait for the response and for the background auto-title task to finish
  await page.waitForTimeout(2000);

  // 6. Click "Historial" button to see the chats list
  const historyBtn = panel.locator('.agent-header-btn[title="Historial de conversaciones"]');
  await expect(historyBtn).toBeVisible();
  await historyBtn.click();

  // Verify list view is rendered
  const listContainer = panel.locator('.agent-conv-list');
  await expect(listContainer).toBeVisible();
  
  // Verify at least one chat item is listed
  const chatItem = listContainer.locator('.agent-conv-item').first();
  await expect(chatItem).toBeVisible();
  
  // The first item should contain the user text or the autogenerated title
  await expect(chatItem.locator('.agent-conv-title')).not.toBeEmpty();

  // 7. Click "Nueva conversación" (➕) button in the header
  const newChatBtn = panel.locator('.agent-header-btn[title="Nueva conversación"]');
  await expect(newChatBtn).toBeVisible();
  await newChatBtn.click();

  // Verify it switches back to chat mode and has cleared messages (shows seed welcome)
  await expect(listContainer).not.toBeVisible();
  const welcomeMsg = panel.locator('.agent-msg.role-agent').first();
  await expect(welcomeMsg).toBeVisible();
  await expect(welcomeMsg).toContainText('Zenith Agent');

  // 8. Go back to history list and delete the second chat
  await historyBtn.click();
  await expect(listContainer).toBeVisible();

  // Get initial chats count
  const initialCount = await listContainer.locator('.agent-conv-item').count();
  expect(initialCount).toBeGreaterThanOrEqual(2);

  // Click delete trash can icon on the second chat item
  const trashBtn = listContainer.locator('.agent-conv-item').nth(1).locator('.agent-conv-delete');
  await trashBtn.click();

  // Wait for sync and verify count decreased
  await page.waitForTimeout(500);
  const postCount = await listContainer.locator('.agent-conv-item').count();
  expect(postCount).toBe(initialCount - 1);
});
